premier_league_analytics:
  target: ci
  outputs:
    ci:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('GCP_SERVICE_ACCOUNT_FILE') }}"
      project: "pl-football-analytics"
      dataset: "football_analytics"
      location: "EU"
      threads: 4
      priority: interactive
