premier_league_analytics:
  target: ci
  outputs:
    ci:
      type: bigquery
      method: service-account-json
      keyfile_json: "{{ env_var('7d994e79a010ca9c0ee90da958543c43d7d6a6fc') }}"
      project: "pl-football-analytics"
      dataset: "football_analytics"
      location: "EU"
      threads: 4
      priority: interactive
